FROM localhost/presto

ARG MIRROR

RUN curl -Lso "${PRESTO_HOME}/bin/presto" "${MIRROR}/maven2/com/facebook/presto/presto-cli/${PRESTO_VERSION}/presto-cli-${PRESTO_VERSION}-executable.jar" \
    && chmod +x "${PRESTO_HOME}/bin/presto"

ENTRYPOINT ["presto", \
            "--server", "localhost:8004", \
            "--catalog", "hive", \
            "--schema", "default"]
