FROM localhost/base

USER root

VOLUME /mnt/data

RUN mkdir -p /mnt/data/postgresql \
    && chown main:main /mnt/data/postgresql

RUN chown -R main:main /var/run/postgresql

RUN dnf install -y --nodocs postgresql-server \
    && dnf clean all

COPY zoneinfo "/usr/share/zoneinfo"

USER main

COPY entrypoint.sh entrypoint.sh
COPY postgresql.conf postgresql.conf

ENTRYPOINT "./entrypoint.sh"
