FROM localhost/base

USER root

RUN dnf install -y --nodocs postgresql-server \
    && dnf clean all

RUN chown -R main:main /var/run/postgresql

COPY zoneinfo "/usr/share/zoneinfo"

USER main

COPY entrypoint.sh entrypoint.sh
COPY postgresql.conf postgresql.conf

ENTRYPOINT "./entrypoint.sh"
