FROM localhost/hadoop

USER main

ARG MIRROR

ARG SPARK_VERSION
ENV SPARK_VERSION ${SPARK_VERSION}
RUN curl -Lfso spark.tar.gz "${MIRROR}/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-without-hadoop.tgz" \
    && tar -xzf spark.tar.gz \
    && mv "spark-${SPARK_VERSION}-bin-without-hadoop" spark \
    && rm spark.tar.gz

ENV SPARK_HOME /home/main/spark

RUN rm -r "${SPARK_HOME}/conf"
COPY conf "${SPARK_HOME}/conf"

ENV PATH "${SPARK_HOME}/bin:$PATH"

COPY entrypoint.sh entrypoint.sh

ENTRYPOINT "./entrypoint.sh"
