FROM localhost/jdk-11

USER main

ARG MIRROR
ARG ES_VERSION
ENV ES_VERSION ${ES_VERSION}

RUN curl -Lso es.tar.gz "${MIRROR}/downloads/elasticsearch/elasticsearch-${ES_VERSION}-linux-x86_64.tar.gz" \
    && tar -xzf es.tar.gz \
    && mv "elasticsearch-${ES_VERSION}" elasticsearch \
    && rm es.tar.gz

ENV ES_HOME /home/main/elasticsearch

ENV PATH "${ES_HOME}/bin:$PATH"
