FROM localhost/jdk-11

USER root

VOLUME /mnt/data

RUN mkdir -p /mnt/data/presto \
    && chown main:main /mnt/data/presto

RUN dnf install -y --nodocs less python3 \
    && dnf clean all

USER main

ARG MIRROR
ARG PRESTO_VERSION=0.235.1
ENV PRESTO_VERSION ${PRESTO_VERSION}

RUN curl -Lfso presto.tar.gz "${MIRROR}/maven2/com/facebook/presto/presto-server/${PRESTO_VERSION}/presto-server-${PRESTO_VERSION}.tar.gz" \
    && tar -xzf presto.tar.gz \
    && mv "presto-server-${PRESTO_VERSION}" presto \
    && rm presto.tar.gz

ENV PRESTO_HOME /home/main/presto

COPY etc "${PRESTO_HOME}/etc"

ENV PATH "${PRESTO_HOME}/bin:$PATH"

ENTRYPOINT ["launcher", "run"]
