FROM localhost/hadoop

USER root

VOLUME /mnt/data

RUN mkdir -p /mnt/data/hive \
    && chown main:main /mnt/data/hive

RUN microdnf install --nodocs postgresql postgresql-jdbc \
    && microdnf clean all

USER main

ARG MIRROR

ARG HIVE_VERSION
ENV HIVE_VERSION ${HIVE_VERSION}
RUN curl -Lso hive.tar.gz "${MIRROR}/hive/hive-${HIVE_VERSION}/apache-hive-${HIVE_VERSION}-bin.tar.gz" \
    && tar -xzf hive.tar.gz \
    && mv "apache-hive-${HIVE_VERSION}-bin" hive \
    && rm hive.tar.gz

ENV HIVE_HOME /home/main/hive
ENV METASTORE_HOME /home/main/hive

RUN rm ${HIVE_HOME}/lib/guava-*.jar \
    && cp ${HADOOP_HOME}/share/hadoop/common/lib/guava-*-jre.jar "${HIVE_HOME}/lib/"

COPY hive-site.xml "${HIVE_HOME}/conf/hive-site.xml"
COPY metastore-site.xml "${METASTORE_HOME}/conf/metastore-site.xml"

ENV PATH "${HADOOP_HOME}/bin:${HIVE_HOME}/bin:$PATH"

COPY entrypoint.sh entrypoint.sh

ENTRYPOINT "./entrypoint.sh"
