FROM registry.fedoraproject.org/fedora-minimal:32

RUN microdnf install --nodocs curl findutils procps which tar \
    && microdnf clean all

RUN groupadd --system --gid 1001 main \
    && useradd --no-log-init --system --create-home --gid main --uid 2001 main

WORKDIR /home/main

ENTRYPOINT bash
