FROM fedora:32

RUN dnf install -y --nodocs findutils procps which \
    && dnf clean all

RUN groupadd --system --gid 1001 main \
    && useradd --no-log-init --system --create-home --gid main --uid 2001 main

WORKDIR /home/main

ENTRYPOINT bash
