FROM localhost/base

VOLUME /mnt/data

RUN mkdir -p /mnt/data/minio \
    && chown main:main /mnt/data/minio

USER main

ARG MIRROR
ARG MINIO_VERSION
ENV MINIO_VERSION ${MINIO_VERSION}

RUN mkdir bin \
    && curl -Lfso bin/minio "${MIRROR}/server/minio/release/linux-amd64/archive/minio.RELEASE.${MINIO_VERSION}" \
    && chmod +x bin/minio

ENV PATH "/home/main/bin:$PATH"

ENV MINIO_UPDATE off
ENV MINIO_ACCESS_KEY minio_ak
ENV MINIO_SECRET_KEY minio_sk

ENV MINIO_HTTP_TRACE /dev/stdout

ENTRYPOINT ["minio", "server", \
            "--address", ":8005", \
            "/mnt/data/minio"]
