FROM localhost/base

USER main

ARG MIRROR
ARG MINIO_VERSION=2020-06-22T03-12-50Z
ENV MINIO_VERSION ${MINIO_VERSION}

RUN mkdir bin \
    && curl -Lfso bin/minio "${MIRROR}/server/minio/release/linux-amd64/archive/minio.RELEASE.${MINIO_VERSION}" \
    && chmod +x bin/minio

ENV PATH "/home/main/bin:$PATH"

ENV MINIO_UPDATE off
ENV MINIO_ACCESS_KEY minio_ak
ENV MINIO_SECRET_KEY minio_sk

COPY entrypoint.sh entrypoint.sh

ENTRYPOINT "./entrypoint.sh"
